title: Free Joomla! Extensions by naftee.com
description: Xchimp2 is a plugin to automatically sync your Joomla! users with your Mailchimp audience
url: "https://naftee.com"
baseurl: "/Xchimp2"
github_username: brettvac

author:
  twitter: naftee
  name: Brett Vachon

google_analytics: G-DP5DG417G7

theme: jekyll-theme-cayman

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap